import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SkeletonTheme } from "react-loading-skeleton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkeletonTheme baseColor="#303030" highlightColor="#3d3d3d">
          {children}
        </SkeletonTheme>
      </body>
    </html>
  );
}
